### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ryan-snyder** [ryan-snyder/cabbly-react-native#1]
- [x] Set up react-native
- [x] Set up firebase
- [x] add login stuff
- [ ] Register in google apis (specifically google maps)
- [ ] Add basic api functions
- [ ] Add ride accept/decline functionality
- [x] riders/drivers same app or different????
- [x] Add eslint and prettier

Once I go to startupzone then:
- [ ] Make Website
Once Basic app is done and I go to startupzone then:

- [ ] Trademark stuff
- [ ] logo design, website design?
- [ ] Marketing stuff

**Comment by ryan-snyder** [comment]
Apparently uber now allows double sign in to sign in for driver or rider from the same app. I think that is the route we will go

**Comment by ryan-snyder** [comment]
Closing issue because we are using trello now
